config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages_controller/index'
  #get 'static_pages_controller/secret'
  devise_for :users
  
  resources :attendances
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, foreign_key: 'attended_event_id'
  belongs_to :host, class_name: 'User'
  has_many :guests, through: :attendances, source: :guest

  validates :start_date, presence: true
  validates :duration, presence: true, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :title, presence: true, length: {minimum: 5, maximum:140}
  validates :description, presence: true, length: {minimum: 20, maximum:1000}
  validates :price, presence: true, numericality: { :only_integer =>true }, :inclusion => { :in => 1..1000 }
  validates :location, presence: true
  
  validate :start_date_cannot_be_in_the_past
  
  validate :duration_must_be_multiple_of_5

  # instance methods for display
  def display_start_date
    start_date.strftime("%a, %b %-d")
  end

  def display_end_date
    (start_date + duration * 60).strftime("%A - %B %-d - %Hh%M")
  end
  
  private
  # custom validator for start date
  def start_date_cannot_be_in_the_past
    errors.add(:start_date, 'cannot be in the past') if
    start_date < Time.zone.today
  end

  # custom validator for duration
  def duration_must_be_multiple_of_5
    errors.add(:duration, 'must be a multiple of 5') if
    duration%5 != 0
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :set_host, only: %i[ new edit ]
  before_action :authenticate_user!, except: %i[ index ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :start_date, :duration, :description, :price, :location, :host_id)
    end

    def set_host
      @host = current_user
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, step: 5 %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% content_for :title, "My Event Brite" %>

      <!-- Jumbotron -->
      <div class="jumbotron" style="background-image: url('/jumbo.jpg');">
        <div class="container">
          <h1 class="display-3">My Event Brite</h1>
          <h3>Rejoins ou créés tes évènements !</h3>
        </div>
      </div>

      <!-- Actual display of events -->
      <div class="container w-75">
        <!-- Example row of columns -->
        <div class="row">
          <% @events.each do |event| %>
            <div class="col-md-4 py-2">
              <div class="card h-100 border-secondary">
                <div class="card-body">
                  <h2 class="card-title"><%= event.title %></h2>
                  <h5 class="card-subtitle mb-2 text-danger"><%= event.display_start_date %></h5>
                  <p class="card-text"><%= event.description %></p>
                  <p><%= link_to 'View details', event, class: 'btn btn-info' %>
                  <p class='text-secondary'><%= event.location %></p>
                </div> <!-- /card-body -->
              </div> <!-- /card -->
            </div> <!-- /col-md-4 -->
          <% end %>
        </div> <!-- /row -->

        <hr>

      </div> <!-- /container -->

<!--
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <%# @events.each do |event| %>
      <tr>
        <td><%#= event.title %></td>
        <td><%#= event.start_date %></td>
        <td><%#= event.duration %></td>
        <td><%#= event.description %></td>
        <td><%#= event.location %></td>
        <td><%#= event.price %></td>
        <td><%#= link_to 'Show', event %></td>
        <td><%#= link_to 'Edit', edit_event_path(event) %></td>
        <td><%#= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Event', new_event_path %>
-->

app/views/events/new.html.erb
<% content_for :title, 'New event' %>

<div class="alert alert-dark text-center" role="alert">
  Ceci est la page pour créer un nouvel évènement !
</div>

<div class="container px-2 mx-5">
  <h1>Quel évènement souhaites-tu publier ?</h1>

  <hr/>

  <%= form_with(model: @event, local: true) do |form| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">

      <div class="field">
        <%= form.label :title %><br />
        <%= form.text_field :title %>
      </div>

      <hr/>

      <div class="field">
        <%= form.label :start_date %><br />
        <%= form.datetime_select :start_date, { 
          ampm: false, order: [:day, :month, :year], 
          prompt: true, start_year: Time.now.year, } %>
      </div>

      <hr/>

      <div class="field">
        <%= form.label :duration %><br />
        <%= form.number_field :duration,step: 5 %>
      </div>

      <hr/>

      <div class="field">
        <%= form.label :description %><br />
        <%= form.text_area :description, rows: 5, class: 'w-50'  %>
      </div>

      <hr/>

      <div class="field">
        <%= form.label :price %><br />
        <%= form.number_field :price %>
      </div>

      <hr/>

      <div class="field">
        <%= form.label :location %><br />
        <%= form.text_field :location %>
      </div>

      <%= form.hidden_field :host_id, value: @host.id %>

      <hr/>

      <div class="actions"><br />
        <%= form.submit "Create event", class: 'btn btn-lg btn-success' %>
      </div>

    </div> <!-- /form-group -->
  <% end %>



</div> <!-- /container-fluid -->

<hr/>

<%= link_to 'Back to homepage', events_path, class: 'btn btn-lg btn-info mx-5 px-5' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>