config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages_controller/index'
  #get 'static_pages_controller/secret'
  devise_for :users
  
  resources :attendances
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!--Title changes depending on the view -->
    <title><%= yield(:title) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class='bg-light'>

  <header>
    <!-- Bootstrap navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <a class="navbar-brand" href="#">
    <img src="/youhou.png" width="30" height="30" alt=""/>
  </a>
      <%= link_to 'MyEventBrite', events_path, :class => 'navbar-brand' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Add an event', new_event_path, :class => 'nav-link' %>
          </li>
        </ul>

        <!-- Dropdowns depending on session status -->
        <ul class="navbar-nav ml-auto">
          <!-- if connected, profile and logout options -->
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.first_name %>
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'My profile', user_path(current_user.id), :class => "dropdown-item text-light" %>
                <%= link_to 'Log  out', destroy_user_session_path,method: :delete, :class => "dropdown-item text-light" %>
              </div>
            </li>

          <!-- if not connected, login and signup options -->
          <% else%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Log in / Sign up
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'Log in', new_user_session_path, :class => "dropdown-item text-light" %>
                <%= link_to 'Sign up', new_user_registration_path, :class => "dropdown-item text-light" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Displaying alerts and notices -->
  <% if notice || alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <% end %>
  
  <!-- Getting content from the other views -->
  <main role='main'>
    <%= yield %>
  </main>
  
  </body>
</html>